# Generated by Django 4.2.7 on 2025-07-06 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('FY', 'First Year'), ('SY', 'Second Year'), ('TY', 'Third Year'), ('LY', 'Last Year')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='PreRegisteredStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('year_of_study', models.CharField(choices=[('FY', 'First Year'), ('SY', 'Second Year'), ('TY', 'Third Year'), ('LY', 'Last Year')], max_length=2)),
                ('full_name', models.CharField(max_length=100)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_students', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pre_registered_students',
            },
        ),
        migrations.CreateModel(
            name='EmbeddedAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('student_performance', 'Student Performance'), ('test_performance', 'Test Performance'), ('live_results', 'Live Results'), ('class_overview', 'Class Overview'), ('behavioral_insights', 'Behavioral Insights')], max_length=50)),
                ('embed_code', models.TextField(blank=True)),
                ('embed_password', models.CharField(max_length=100)),
                ('settings', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedded_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'embedded_analytics',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('year_applicable', models.CharField(choices=[('FY', 'First Year'), ('SY', 'Second Year'), ('TY', 'Third Year'), ('LY', 'Last Year')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subjects',
                'unique_together': {('teacher', 'code')},
            },
        ),
    ]
